name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name for the release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
      plugin_name:
        description: 'Name of the plugin to be released'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # You can specify the Node.js version as needed

    - name: Install NPM dependencies
      run: npm install

    - name: Install Composer dependencies without dev
      run: composer install --no-dev

    - name: Get version and plugin name from user input
      run: |
        VERSION=${{ github.event.inputs.version }}
        PLUGIN_NAME=${{ github.event.inputs.plugin_name }}
        # Ensure that the version is prefixed with "v" for a valid tag name
        if [[ $VERSION != v* ]]; then
          VERSION="v${VERSION}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PLUGIN_NAME=$PLUGIN_NAME" >> $GITHUB_ENV

    - name: Cleanup unnecessary files
      run: |
        rm -f composer.json composer.lock package.json package-lock.json README.md

    - name: Zip the plugin
      run: |
        zip -r "${{ env.PLUGIN_NAME }}-package.zip" . -x "*.git*" -x "*.github*" -x "*.yml" -x "phpunit.xml" -x "tests/**" -x "docs/**"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.PLUGIN_NAME }} ${{ env.VERSION }}
        body: "Release of ${{ env.PLUGIN_NAME }} plugin version ${{ env.VERSION }}."
        draft: false
        prerelease: false

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./${{ env.PLUGIN_NAME }}-package.zip"
        asset_name: "${{ env.PLUGIN_NAME }}-package.zip"
        asset_content_type: application/zip